name: netflix
services:
  db:
    image: mysql:8.0
    container_name: mysql_container
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: netflix
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3307:3307"
    volumes:
      - ./init-scripts:/docker-entrypoint-initdb.d

  backend:
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: backend_container
    ports:
      - "8001:8001"
    volumes:
      - .:/app  # Enables hot reload for app directory, only for local dev., delete for production
    depends_on:
      - db
volumes:
  db_data:
